//! One-shot SpiderMonkey setup so `cargo build` on a fresh machine yields a
//! working parser:
//!
//!   1. shallow-clone mozilla-central at a pinned revision
//!   2. `mach bootstrap` — downloads Mozilla's vendored clang (+ libclang)
//!      into `~/.mozbuild/clang`
//!   3. `mach configure` — debug JS-shell-only build into `obj-js`
//!   4. `mach build pre-export export` — runs the code generators that
//!      produce headers CacheIR.cpp includes (no C++ is compiled)
//!   5. `mach build-backend -b CompileDB` — emits compile_commands.json
//!
//! Every step is skipped when its output already exists, so rebuilds are
//! free. The resulting paths are exported to the crate as
//! `PHOENIX_MOZ_CENTRAL` and `PHOENIX_COMPILE_DB`.
//!
//! Environment overrides:
//!   PHOENIX_MOZ_CENTRAL   checkout location (default: ./mozilla-central under
//!                         the directory `cargo` was invoked from)
//!   PHOENIX_MOZ_REV       mozilla-central revision to pin (default below)
//!   PHOENIX_SKIP_SETUP=1  do nothing (offline builds / CI); the binary then
//!                         needs the paths given explicitly on the command line
//!   MOZBUILD_STATE_PATH   where mach keeps toolchains (mach's own variable;
//!                         default ~/.mozbuild)

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::{env, fs};

const MOZ_CENTRAL_URL: &str = "https://github.com/mozilla-firefox/firefox.git";
/// mozilla-central tip as of 2026-09-18. Must be the full sha: git only
/// allows fetching an unadvertised commit by its complete object name.
const MOZ_CENTRAL_REV: &str = "f35f2f1f3ae810c36ac678d269129d54040d6994";

const MOZCONFIG: &str = "\
# Generated by phoenix/build.rs. Debug JS-shell-only build; nothing is compiled,
# we only need configure + the export tier for generated headers.
ac_add_options --enable-project=js
ac_add_options --enable-debug
ac_add_options --disable-optimize
ac_add_options --disable-tests
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-js
";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    for v in [
        "PHOENIX_MOZ_CENTRAL",
        "PHOENIX_MOZ_REV",
        "PHOENIX_SKIP_SETUP",
        "MOZBUILD_STATE_PATH",
    ] {
        println!("cargo:rerun-if-env-changed={v}");
    }

    // Default the checkout into the directory `cargo` was invoked from. A build
    // script's own cwd is the crate's manifest dir, not where the user ran the
    // command, but cargo forwards the invocation dir in $PWD; fall back to the
    // manifest dir if it's unset (e.g. a non-shell invocation).
    let invocation_dir = env::var_os("PWD")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()));
    let moz_central = env::var_os("PHOENIX_MOZ_CENTRAL")
        .map(PathBuf::from)
        .unwrap_or_else(|| invocation_dir.join("mozilla-central"));
    let moz_central = absolute(&moz_central);
    let objdir = moz_central.join("obj-js");
    let compile_db = objdir.join("compile_commands.json");

    println!(
        "cargo:rustc-env=PHOENIX_MOZ_CENTRAL={}",
        moz_central.display()
    );
    println!(
        "cargo:rustc-env=PHOENIX_COMPILE_DB={}",
        compile_db.display()
    );

    if env::var_os("PHOENIX_SKIP_SETUP").is_some() {
        return;
    }

    let setup = Setup {
        moz_central: moz_central.clone(),
        objdir,
        mozconfig: moz_central.join("mozconfig-phoenix"),
        log: PathBuf::from(env::var("OUT_DIR").unwrap()).join("setup.log"),
    };
    setup.clone_tree();
    setup.bootstrap();
    setup.configure();
    setup.export();
    setup.compile_db();
    assert!(
        compile_db.is_file(),
        "setup finished but {} is missing",
        compile_db.display()
    );
}

struct Setup {
    moz_central: PathBuf,
    objdir: PathBuf,
    mozconfig: PathBuf,
    log: PathBuf,
}

impl Setup {
    fn clone_tree(&self) {
        let rev = env::var("PHOENIX_MOZ_REV").unwrap_or_else(|_| MOZ_CENTRAL_REV.into());
        if self.moz_central.join(".git").exists() {
            // Already cloned; only re-pin if a different revision was asked for.
            let head = self.git_output(&["rev-parse", "HEAD"]);
            if head.starts_with(&rev) {
                return;
            }
            self.warn(&format!("mozilla-central at {head}, switching to {rev}"));
            self.run(
                "git",
                &["fetch", "--depth", "1", "origin", &rev],
                &self.moz_central,
            );
            self.run(
                "git",
                &["checkout", "--detach", "FETCH_HEAD"],
                &self.moz_central,
            );
            return;
        }
        self.warn(&format!(
            "cloning mozilla-central into {} (~2 GB, several minutes)",
            self.moz_central.display()
        ));
        let parent = self.moz_central.parent().unwrap();
        fs::create_dir_all(parent).unwrap();
        let target = self.moz_central.to_string_lossy().into_owned();
        // GitHub allows fetching an arbitrary reachable commit by sha, so pin
        // without pulling history: clone tip shallowly, then fetch the sha.
        self.run(
            "git",
            &[
                "clone",
                "--depth",
                "1",
                "--no-checkout",
                MOZ_CENTRAL_URL,
                &target,
            ],
            parent,
        );
        if self.git_output(&["rev-parse", "HEAD"]).starts_with(&rev) {
            self.run("git", &["checkout", "--detach", "HEAD"], &self.moz_central);
        } else {
            self.run(
                "git",
                &["fetch", "--depth", "1", "origin", &rev],
                &self.moz_central,
            );
            self.run(
                "git",
                &["checkout", "--detach", "FETCH_HEAD"],
                &self.moz_central,
            );
        }
    }

    fn bootstrap(&self) {
        let lib = mozbuild_state().join("clang/lib");
        if libclang_in(&lib) {
            return;
        }
        self.warn("running `mach bootstrap` to fetch the vendored clang (~1 GB download)");
        self.mach(&[
            "--no-interactive",
            "bootstrap",
            "--application-choice=js",
            "--no-system-changes",
        ]);
        assert!(
            libclang_in(&lib),
            "mach bootstrap finished but no libclang under {}",
            lib.display()
        );
    }

    fn configure(&self) {
        if self.objdir.join("config.status").exists() {
            return;
        }
        fs::write(&self.mozconfig, MOZCONFIG).unwrap();
        self.warn("running `mach configure`");
        self.mach(&["configure"]);
    }

    fn export(&self) {
        if self
            .objdir
            .join("js/src/jit/CacheIROpsGenerated.h")
            .exists()
        {
            return;
        }
        self.warn("running `mach build pre-export export` (generated headers)");
        self.mach(&["build", "pre-export", "export"]);
    }

    fn compile_db(&self) {
        if self.objdir.join("compile_commands.json").exists() {
            return;
        }
        self.warn("running `mach build-backend -b CompileDB`");
        self.mach(&["build-backend", "-b", "CompileDB"]);
    }

    fn mach(&self, args: &[&str]) {
        let mut cmd = Command::new("./mach");
        cmd.args(args)
            .current_dir(&self.moz_central)
            .env("MOZCONFIG", &self.mozconfig)
            // Cargo sets these for the build script; they confuse mach's own
            // cargo/rustc discovery when it configures the tree.
            .env_remove("CARGO")
            .env_remove("RUSTC")
            .env_remove("RUSTFLAGS")
            .env_remove("CARGO_ENCODED_RUSTFLAGS");
        self.exec(cmd);
    }

    fn run(&self, prog: &str, args: &[&str], cwd: &Path) {
        let mut cmd = Command::new(prog);
        cmd.args(args).current_dir(cwd);
        self.exec(cmd);
    }

    /// Run a command with stdout/stderr appended to the setup log; cargo hides
    /// build-script output, so this is the only place progress is visible.
    fn exec(&self, mut cmd: Command) {
        let log = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.log)
            .unwrap();
        let log2 = log.try_clone().unwrap();
        cmd.stdin(Stdio::null()).stdout(log).stderr(log2);
        let desc = format!("{cmd:?}");
        let status = cmd
            .status()
            .unwrap_or_else(|e| panic!("failed to spawn {desc}: {e}"));
        if !status.success() {
            panic!(
                "phoenix setup step failed ({status}): {desc}\nsee {} for output",
                self.log.display()
            );
        }
    }

    fn git_output(&self, args: &[&str]) -> String {
        let out = Command::new("git")
            .args(args)
            .current_dir(&self.moz_central)
            .output()
            .unwrap();
        String::from_utf8_lossy(&out.stdout).trim().to_string()
    }

    fn warn(&self, msg: &str) {
        println!("cargo:warning=phoenix: {msg} [log: {}]", self.log.display());
    }
}

fn mozbuild_state() -> PathBuf {
    env::var_os("MOZBUILD_STATE_PATH")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env::var_os("HOME").unwrap()).join(".mozbuild"))
}

fn libclang_in(dir: &Path) -> bool {
    ["libclang.dylib", "libclang.so"]
        .iter()
        .any(|n| dir.join(n).exists())
}

fn absolute(p: &Path) -> PathBuf {
    let p = if p.is_absolute() {
        p.to_path_buf()
    } else {
        env::current_dir().unwrap().join(p)
    };
    // Normalise `..` without requiring the path to exist yet.
    let mut out = PathBuf::new();
    for c in p.components() {
        match c {
            std::path::Component::ParentDir => {
                out.pop();
            }
            std::path::Component::CurDir => {}
            c => out.push(c),
        }
    }
    out
}
