#!/bin/bash
set -euo pipefail

# Verifies the functional spec, then three controls that must FAIL. The
# controls are the evidence that the spec is non-vacuous and that the
# generator's two MOZ_ASSERTs are load-bearing for correctness.
#
# Each control is generated by mutating the spec, so there is no second copy
# of the source to drift.

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
spec="${here}/stubs/compare_int32.cachet"
pass=0; fail=0

run() {  # run <name> <expected: bugs|clean>
  local name="$1" expect="$2" out
  out="$("${here}/compile-verify.sh" "${name}" 2>&1 | grep -cE "Program has no bugs" || true)"
  local got="bugs"; [[ "${out}" == "1" ]] && got="clean"
  if [[ "${got}" == "${expect}" ]]; then
    printf '  ok    %-22s (%s)\n' "${name}" "${got}"; pass=$((pass+1))
  else
    printf '  FAIL  %-22s expected %s, got %s\n' "${name}" "${expect}" "${got}"; fail=$((fail+1))
  fi
}

mutate() {  # mutate <name> <python-replacement>
  python3 - "$1" "$2" "${spec}" "${here}" <<'PY'
import sys, pathlib
name, mode, spec, here = sys.argv[1:5]
s = pathlib.Path(spec).read_text()
cuts = {
  "drop_null_guard": ("""        assume !(Value::isNull(lhsValue) || Value::isNull(rhsValue))
            || !JSOp::isEqualityOp(jsop);""", "        // removed"),
  "drop_strict_guard": ("""        assume !JSOp::isStrictEqualityOp(jsop)
            || Value::isSameType(lhsValue, rhsValue);""", "        // removed"),
  "negated_postcond": ("Value::fromBool(compareResult(jsop, lhsValue, rhsValue))",
                       "Value::fromBool(!compareResult(jsop, lhsValue, rhsValue))"),
}
old, new = cuts[mode]
assert old in s, mode
pathlib.Path(here, "stubs", name + ".cachet").write_text(s.replace(old, new))
PY
}

echo "spec (must verify):"
run compare_int32 clean

echo "controls (must fail):"
for m in drop_null_guard drop_strict_guard negated_postcond; do
  mutate "${m}" "${m}"
  run "${m}" bugs
  rm -f "${here}/stubs/${m}.cachet"
done

echo
echo "${pass} ok, ${fail} failed"
[[ "${fail}" == 0 ]]
